const CartActionTypes = {
    TOGGLE_CART_HIDDEN:"TOGGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    SUBSTRACT_ITEM: "SUBSTRACT_ITEM",
    CLEAR_CART:  "CLEAR_CART"
}
export default CartActionTypes;